site_name: 100 Days of Machine Learning 🔥 🚀
site_url: https://hg03.github.io/100-Days-Of-Machine-Learning
theme:
  name: material
  logo: assets/logo.svg
  
  palette:
      - scheme: default
        toggle:
          icon: material/toggle-switch-off-outline 
          name: Switch to dark mode
        primary: teal
        accent: purple 
      - scheme: slate 
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode    
        primary: teal
        accent: lime
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hg03
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/harish-gehlot-5338a021a/

